from django.contrib import admin
from .models import (BlogAndNews, CafeProduct, Gallery, MassageTherapist, Position, Procedure, Record, Review, Salon, Schedule, SpaUser, TypeBlogAndNews, TypeCafeProduct, TypeCategories, TypeGallery, SpaСategories)

admin.site.register(SpaUser)
admin.site.register(Salon)
admin.site.register(MassageTherapist)
admin.site.register(SpaСategories)
admin.site.register(TypeCategories)
admin.site.register(Review)
admin.site.register(Position)
admin.site.register(Procedure)
admin.site.register(CafeProduct)
admin.site.register(TypeCafeProduct)
admin.site.register(BlogAndNews)
admin.site.register(TypeBlogAndNews)
admin.site.register(TypeGallery)
admin.site.register(Gallery)
admin.site.register(Schedule)
admin.site.register(Record)
