from django.contrib import admin
from .models import (BlogAndNews, CafeProduct, Composition, Gallery, MassageTherapist, Position, Review, Salon, SpaUser, TypeBlogAndNews,     TypeCafeProduct, TypeCategories, TypeGallery, SpaСategories, CategoriesSession)

admin.site.register(SpaUser)
admin.site.register(Salon)
admin.site.register(MassageTherapist)
admin.site.register(SpaСategories)
admin.site.register(TypeCategories)
admin.site.register(Composition)
admin.site.register(Review)
admin.site.register(Position)
admin.site.register(CategoriesSession)
admin.site.register(CafeProduct)
admin.site.register(TypeCafeProduct)
admin.site.register(BlogAndNews)
admin.site.register(TypeBlogAndNews)
admin.site.register(TypeGallery)
admin.site.register(Gallery)
