# Generated by Django 5.0.6 on 2024-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spauser',
            name='wallet',
        ),
        migrations.AddField(
            model_name='spauser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
