# Generated by Django 5.0.6 on 2024-06-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0006_spaservicestype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SpaСategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories_image', models.ImageField(blank=True, null=True, upload_to='categories_image/')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('type_categories_image', models.ImageField(blank=True, null=True, upload_to='type_categories_image/')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='myspa.composition')),
            ],
        ),
        migrations.DeleteModel(
            name='SpaServicesType',
        ),
        migrations.AddField(
            model_name='spaсategories',
            name='type_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_categories', to='myspa.typecategories'),
        ),
    ]
