# Generated by Django 5.0.6 on 2024-06-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0008_day_therapistavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaсategories',
            name='type_categories',
        ),
        migrations.AddField(
            model_name='typecategories',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_categories', to='myspa.spaсategories'),
        ),
    ]
