# Generated by Django 5.0.6 on 2024-06-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0009_remove_spaсategories_type_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaсategories',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
