# Generated by Django 5.0.6 on 2024-06-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0011_massagetherapist_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massagetherapist',
            name='type_categories',
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type_categories', models.ManyToManyField(related_name='type_categories', to='myspa.typecategories')),
            ],
        ),
        migrations.AddField(
            model_name='massagetherapist',
            name='position',
            field=models.ManyToManyField(related_name='position', to='myspa.position'),
        ),
    ]
