# Generated by Django 5.0.6 on 2024-06-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0012_remove_massagetherapist_type_categories_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spauser',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
