# Generated by Django 5.0.6 on 2024-06-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0013_alter_spauser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spauser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
