# Generated by Django 5.0.6 on 2024-06-17 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0014_alter_spauser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecategories',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=3600), 'Regular'), (datetime.timedelta(seconds=5400), 'Long')]),
        ),
    ]
