# Generated by Django 5.0.6 on 2024-06-18 20:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0018_rename_cateroriessession_categoriessession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCafeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='categoriessession',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), '30'), (datetime.timedelta(seconds=3600), '60'), (datetime.timedelta(seconds=5400), '90'), (datetime.timedelta(seconds=7200), '120')]),
        ),
        migrations.CreateModel(
            name='CafeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('composition', models.TextField(max_length=250)),
                ('type_cafe_product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_categories', to='myspa.typecafeproduct')),
            ],
        ),
    ]
