# Generated by Django 5.0.6 on 2024-06-19 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0019_typecafeproduct_alter_categoriessession_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBlogAndNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogAndNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='blog_image/')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='blog_image/')),
                ('type_blog_and_news', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_blog_and_news', to='myspa.typeblogandnews')),
            ],
        ),
    ]
