# Generated by Django 5.0.6 on 2024-06-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0021_typegallery_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spauser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
