# Generated by Django 5.0.6 on 2024-06-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0024_alter_spauser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='spauser',
            name='name',
            field=models.CharField(blank=True, default='name', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='spauser',
            name='surname',
            field=models.CharField(blank=True, default='surname', max_length=16, null=True),
        ),
    ]
