# Generated by Django 5.0.6 on 2024-06-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0025_spauser_name_spauser_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spauser',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='spauser',
            name='surname',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
