# Generated by Django 5.0.6 on 2024-06-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0026_alter_spauser_name_alter_spauser_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spauser',
            name='name',
            field=models.CharField(blank=True, default='1', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='spauser',
            name='surname',
            field=models.CharField(blank=True, default='2', max_length=16, null=True),
        ),
    ]
