# Generated by Django 5.0.6 on 2024-07-02 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0028_remove_spauser_name_remove_spauser_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistavailability',
            name='day',
        ),
        migrations.RemoveField(
            model_name='therapistavailability',
            name='therapist',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myspa.massagetherapist')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myspa.categoriessession')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myspa.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='TherapistAvailability',
        ),
    ]
