# Generated by Django 5.0.6 on 2024-07-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0029_remove_therapistavailability_day_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesSession',
            new_name='Procedure',
        ),
    ]
