# Generated by Django 5.0.6 on 2024-07-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0030_rename_categoriessession_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecategories',
            name='composition',
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
    ]
