# Generated by Django 5.0.6 on 2024-07-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0031_remove_typecategories_composition_delete_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='spa_categories',
            field=models.ManyToManyField(related_name='positions', to='myspa.spaсategories'),
        ),
    ]
