# Generated by Django 5.0.6 on 2024-07-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0032_position_spa_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='type_categories',
        ),
    ]
