# Generated by Django 5.0.6 on 2024-07-08 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspa', '0033_remove_position_type_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
